### ISSUE TITLE
Selection rectangle

### ISSUE THREAD

**Issue by fygure** [fygure/Football-Playmaker-App#15]
Selection rectangle for stage. this will involve using a transformer most likely. we can disable the transformer functionalities like resizing and rotating but still might need it to achieve this.

**Comment by KevinZheng14815** [comment]
Completed the selection rectangle state
TODO: now we need to add the transformer.

**Comment by fygure** [comment]
Asking client if this is a must 1/5

**Comment by fygure** [comment]
Not a must, will be refactored and implemented next cycle
