### ISSUE TITLE
Lines

### ISSUE THREAD

**Issue by fygure** [fygure/Football-Playmaker-App#26]
Bezier curves and sharp angle curves

Line end types

Line types

Connected lines from players

**Comment by fygure** [comment]
@ChristopherOosthuizen 
For the lines, take a look at the following:
https://konvajs.org/docs/sandbox/Modify_Curves_with_Anchor_Points.html
https://konvajs.org/docs/sandbox/Connected_Objects.html
(the lines just need to point from a receiver and to an empty space)

As for functionality, lets discuss how we the lines gets initialized on the canvas

**Comment by fygure** [comment]
Ask the client about how exactly they want the lines to be implemented and used.

**Comment by fygure** [comment]
default endpoint for O-line is the perpendicular line and the arrow for the receiver lines

**Comment by fygure** [comment]
![image](https://github.com/fygure/Football-Playmaker-App/assets/92011471/9efb7fd2-2e0d-4ad4-8dc6-d5df851e08e1)

**Comment by fygure** [comment]
pr #83 completed line buttons for stroke and end

**Comment by fygure** [comment]
pr #87 basic line dragging from shape's anchor point. start of line connects with shape upon shape dragging. line can be deleted on context menu, lines are attached to a shape when drawn from shape's anchor point.

TODO: 
- implement all these for Lineman Oval, Defender Oval (currently only works on Receiver Oval)
- complete functionality for line end anchor point (currently a circle)
- then implement bezier curve functionality
- apply line stroke styles based on stencil input
- apply line end styles based on stencil input

**Comment by KevinZheng14815** [comment]
Apply color stencil to line selected.

**Comment by fygure** [comment]
pr #95 
TODO:
- Apply all stencil options to selected line
- Change player shape anchor points to halo to draw from

COMPLETED:
- Drawing lines from shapes
- Drawing lines from anchors
- Quadratic Curve
- Dragging and dropping updates start and ends
- Halo instead of anchor points

**Comment by fygure** [comment]
Possibly need to add a tension option on stencil (0 = sharp, 0.3 = normal, 0.6 = round)

**Comment by fygure** [comment]
pr #100 Line and Stencil utility implemented.
